tier_1_categories:
  tech:
    description: Technology in general, including infrastructure, devices, and digital systems
    sub_tags:
      - operating systems
      - dev environments
      - privacy
      - networking
      - hardware
      - performance tuning

  software:
    description: Software engineering, programming, and tools
    sub_tags:
      - programming
      - APIs
      - open source
      - version control
      - testing
      - automation

  ai:
    description: Artificial Intelligence, Machine Learning, and LLMs
    sub_tags:
      - language models
      - agents
      - embeddings
      - transformers
      - alignment
      - datasets

  systems:
    description: Systems thinking, architectures, workflows, and complex coordination
    sub_tags:
      - feedback loops
      - automation design
      - interop
      - context engineering
      - reliability
      - orchestration

  strategy:
    description: Long-term thinking, planning, tradeoff analysis, and decision-making frameworks
    sub_tags:
      - leverage
      - incentives
      - prioritization
      - power
      - time horizon
      - game theory

  philosophy:
    description: Foundational questions about knowledge, ethics, identity, and meaning
    sub_tags:
      - epistemology
      - ethics
      - metaphysics
      - stoicism
      - existentialism
      - applied philosophy

  psychology:
    description: Mental models, emotional patterns, therapy concepts, human behavior
    sub_tags:
      - trauma
      - attachment
      - motivation
      - regulation
      - self-awareness
      - mental health

  relationships:
    description: Dynamics between people — personal, romantic, or social
    sub_tags:
      - parenting
      - codependency
      - repair
      - boundaries
      - trust
      - communication

  parenting:
    description: Raising children, development, routines, values, and behavior guidance
    sub_tags:
      - neurodivergence
      - routines
      - education
      - conflict
      - modeling
      - emotional development

  health:
    description: Physical and mental well-being
    sub_tags:
      - sleep
      - nutrition
      - medication
      - exercise
      - recovery
      - therapy

  education:
    description: Learning, teaching, pedagogy, and child development
    sub_tags:
      - curriculum
      - self-directed learning
      - Montessori
      - homeschooling
      - edtech
      - mastery

  finance:
    description: Personal finance, macroeconomics, investing, and budgeting
    sub_tags:
      - housing
      - taxes
      - investing
      - equity
      - retirement
      - tradeoffs

  tools:
    description: Utility apps, hardware, devices, and digital tools
    sub_tags:
      - note-taking
      - calendar
      - time tracking
      - organization
      - command-line
      - local-first

  diy:
    description: Practical repairs, physical projects, and hands-on problem solving
    sub_tags:
      - woodworking
      - electrical
      - mounting
      - refinishing
      - gear
      - workshop

  governance:
    description: Structures of control, decision-making, rules, and societal systems
    sub_tags:
      - institutions
      - law
      - power structures
      - democracy
      - community design
      - protocol

  media:
    description: Content formats, storytelling, critique, and media theory
    sub_tags:
      - podcasting
      - publishing
      - narrative design
      - critique
      - distribution
      - curation 