# Atlas Environment Configuration Profiles
# This file defines environment-specific settings that inherit from base configuration

# Base configuration (shared by all environments)
base:
  # Default data directory
  data_directory: "output"

  # Default LLM configuration
  llm_provider: "openrouter"
  llm_model: "mistralai/mistral-7b-instruct:free"
  llm_model_budget: "mistralai/mistral-7b-instruct:free"
  llm_model_premium: "google/gemini-2.0-flash-lite-001"
  llm_model_fallback: "google/gemma-2-9b-it:free"

  # Processing configuration
  max_retries: 3
  processing_timeout: 30
  log_level: "INFO"

  # Feature flags
  podcast_episode_limit: 20
  use_12ft_io_fallback: false
  use_playwright_for_nyt: false

  # Ingestor defaults
  article_ingestor_enabled: true
  podcast_ingestor_enabled: true
  youtube_ingestor_enabled: true
  instapaper_ingestor_enabled: true

  # Transcription defaults
  transcribe_enabled: false
  transcribe_backend: "local"
  whisper_path: "/usr/local/bin/whisper"

# Development environment - optimized for fast iteration and debugging
development:
  # Inherit all base settings
  inherits: base

  # Override specific settings for development
  log_level: "DEBUG"
  max_retries: 1  # Fail fast during development
  processing_timeout: 10  # Shorter timeouts for quick feedback

  # Conservative limits for development
  podcast_episode_limit: 5

  # Enable debug features
  use_12ft_io_fallback: true  # Enable for testing paywall bypass

  # Use faster, cheaper models for development
  llm_model: "mistralai/mistral-7b-instruct:free"
  llm_model_premium: "mistralai/mistral-7b-instruct:free"
  llm_model_budget: "mistralai/mistral-7b-instruct:free"

  # Development data directory
  data_directory: "dev_output"

# Testing environment - optimized for automated testing and CI/CD
test:
  # Inherit all base settings
  inherits: base

  # Override specific settings for testing
  log_level: "WARNING"  # Reduce log noise in tests
  max_retries: 1  # Fail fast in tests
  processing_timeout: 5  # Very short timeout for unit tests

  # Minimal limits for fast tests
  podcast_episode_limit: 1

  # Disable external services for testing
  use_12ft_io_fallback: false
  use_playwright_for_nyt: false

  # Use mock/local models for testing
  llm_provider: "mock"
  llm_model: "mock-model"

  # Disable ingestors that require external APIs
  youtube_ingestor_enabled: false
  instapaper_ingestor_enabled: false

  # Test data directory
  data_directory: "test_output"

# Production environment - optimized for reliability and performance
production:
  # Inherit all base settings
  inherits: base

  # Override specific settings for production
  log_level: "INFO"
  max_retries: 5  # More retries for reliability
  processing_timeout: 60  # Longer timeout for complex operations

  # Production-appropriate limits
  podcast_episode_limit: 50

  # Security-focused settings
  use_12ft_io_fallback: false  # Privacy-conscious default
  use_playwright_for_nyt: false  # Avoid scraping unless explicitly needed

  # Optimized model configuration for production
  llm_model_budget: "mistralai/mistral-7b-instruct:free"
  llm_model_premium: "anthropic/claude-3-sonnet"
  llm_model_fallback: "google/gemini-2.0-flash-lite-001"

  # Production data directory
  data_directory: "production_data"

# Staging environment - similar to production but with more monitoring
staging:
  # Inherit production settings
  inherits: production

  # Override for staging-specific needs
  log_level: "DEBUG"  # More detailed logging for staging
  data_directory: "staging_data"

  # Use cheaper models for staging to reduce costs
  llm_model_premium: "google/gemini-2.0-flash-lite-001"

# Local development with real APIs - for testing with actual services
local-with-apis:
  # Inherit development settings
  inherits: development

  # Enable all services for full local testing
  youtube_ingestor_enabled: true
  instapaper_ingestor_enabled: true

  # Use real LLM provider
  llm_provider: "openrouter"

  # Reasonable limits for local testing with APIs
  podcast_episode_limit: 10
  processing_timeout: 20
