
database:
  path: "data/test_atlas.db"
  backup_path: "backups/test_atlas.db.bak"
  max_size_mb: 1000

connection_pool:
  max_connections: 5
  min_connections: 1
  timeout_seconds: 30
  health_check_interval: 300

cache:
  enabled: true
  max_size: 100
  ttl_seconds: 3600

performance:
  wal_mode: true
  foreign_keys: true
  synchronous: "NORMAL"
  temp_store: "MEMORY"
  mmap_size: 268435456
