#!/usr/bin/env python3
"""
Configuration Validation Script

This script validates the Atlas configuration and provides detailed guidance
for fixing any issues found.

Usage:
    python scripts/validate_config.py
    python scripts/validate_config.py --json  # Output in JSON format
    python scripts/validate_config.py --fix   # Provide fix commands only
"""

import argparse
import json
import sys
from pathlib import Path

# Add the project root to Python path
sys.path.insert(0, str(Path(__file__).parent.parent))

from helpers.config import load_config
from helpers.error_handler import create_error_handler
from helpers.validate import ConfigValidator


def main():
    parser = argparse.ArgumentParser(description="Validate Atlas configuration")
    parser.add_argument(
        "--json", action="store_true", help="Output results in JSON format"
    )
    parser.add_argument("--fix", action="store_true", help="Show only fix commands")
    parser.add_argument(
        "--errors-only", action="store_true", help="Show only errors, not warnings"
    )
    parser.add_argument(
        "--quiet",
        "-q",
        action="store_true",
        help="Quiet mode - only output if there are issues",
    )
    parser.add_argument(
        "--security",
        action="store_true",
        help="Run security-specific validation checks",
    )
    parser.add_argument(
        "--summary",
        action="store_true",
        help="Show error trend analysis and statistics",
    )
    parser.add_argument(
        "--days",
        type=int,
        default=7,
        help="Number of days for error summary (default: 7)",
    )

    args = parser.parse_args()

    try:
        # Load configuration
        config = load_config()

        # Handle special modes
        if args.security:
            run_security_validation(args)
            return
        elif args.summary:
            show_error_summary(config, args)
            return

        # Validate configuration
        validator = ConfigValidator()
        errors, warnings = validator.validate_config(config)

        # Handle different output formats
        if args.json:
            output_json(errors, warnings)
        elif args.fix:
            output_fix_commands(errors, warnings, args.errors_only)
        else:
            output_report(validator, errors, warnings, args.errors_only, args.quiet)

        # Exit with appropriate code
        sys.exit(1 if errors else 0)

    except Exception as e:
        if args.json:
            print(json.dumps({"error": str(e)}, indent=2))
        else:
            print(f"❌ Error loading configuration: {e}")
        sys.exit(2)


def output_json(errors, warnings):
    """Output validation results in JSON format."""
    result = {
        "valid": len(errors) == 0,
        "errors": [
            {
                "field": error.field,
                "message": error.message,
                "severity": error.severity,
                "guidance": error.guidance,
                "fix_command": error.fix_command,
                "documentation_url": error.documentation_url,
            }
            for error in errors
        ],
        "warnings": [
            {
                "field": warning.field,
                "message": warning.message,
                "severity": warning.severity,
                "guidance": warning.guidance,
                "fix_command": warning.fix_command,
                "documentation_url": warning.documentation_url,
            }
            for warning in warnings
        ],
    }
    print(json.dumps(result, indent=2))


def output_fix_commands(errors, warnings, errors_only=False):
    """Output only the fix commands."""
    issues = errors if errors_only else errors + warnings

    if not issues:
        print("# No fix commands needed - configuration is valid!")
        return

    print("#!/bin/bash")
    print("# Atlas Configuration Fix Commands")
    print("# Generated by validate_config.py")
    print()

    for issue in issues:
        if issue.fix_command:
            print(f"# Fix for {issue.field}: {issue.message}")
            print(issue.fix_command)
            print()


def output_report(validator, errors, warnings, errors_only=False, quiet=False):
    """Output the full validation report."""
    if quiet and not errors and not warnings:
        return

    issues_to_show = errors if errors_only else None
    warnings_to_show = [] if errors_only else warnings

    if quiet and not errors:
        return

    report = validator.format_validation_report(errors, warnings_to_show)
    print(report)

    # Add summary statistics
    if not quiet:
        print(f"📊 Validation Summary:")
        print(f"   • Errors: {len(errors)}")
        print(f"   • Warnings: {len(warnings)}")

        if errors:
            print(f"   • Status: ❌ Configuration needs fixes")
        elif warnings:
            print(f"   • Status: ⚠️  Configuration works but has recommendations")
        else:
            print(f"   • Status: ✅ Configuration is optimal")


def run_security_validation(args):
    """Run security-specific validation checks."""
    try:
        from helpers.config import load_config
        from helpers.security import validate_security

        config = load_config()
        security_results, security_report = validate_security(config)

        if args.json:
            result = {
                "security_check_count": len(security_results),
                "checks": [
                    {
                        "check": result.check,
                        "status": result.status,
                        "severity": result.severity,
                        "message": result.message,
                        "recommendation": result.recommendation,
                        "fix_command": result.fix_command,
                    }
                    for result in security_results
                ],
            }
            print(json.dumps(result, indent=2))
        else:
            print(security_report)

    except ImportError:
        print("❌ Security validation not available (helpers.security not found)")
    except Exception as e:
        print(f"❌ Security validation failed: {e}")


def show_error_summary(config, args):
    """Show error trend analysis and statistics."""
    try:
        error_handler = create_error_handler(config)
        summary = error_handler.get_error_summary(days=args.days)

        if args.json:
            print(json.dumps(summary, indent=2))
            return

        print(f"📊 Error Summary ({args.days} days)")
        print("=" * 40)
        print(f"Environment: {summary['environment']}")
        print(f"Total Errors: {summary['total_errors']}")

        if summary["error_categories"]:
            print("\n📈 Error Categories:")
            for category, count in sorted(summary["error_categories"].items()):
                print(f"  {category}: {count}")

        if summary["severity_distribution"]:
            print("\n🚨 Severity Distribution:")
            for severity, count in sorted(summary["severity_distribution"].items()):
                print(f"  {severity}: {count}")

        if summary["recent_errors"]:
            print(f"\n🕐 Recent Errors (last {len(summary['recent_errors'])}):")
            for error in summary["recent_errors"]:
                timestamp = error.get("timestamp", "unknown")
                category = error.get("category", "unknown")
                message = error.get("message", "no message")
                print(f"  {timestamp[:19]} [{category}] {message}")
        else:
            print("\n✅ No recent errors found")

    except Exception as e:
        print(f"❌ Error summary failed: {e}")


if __name__ == "__main__":
    main()
